#!/bin/env python3

import argparse
import json
import operator
import pickle
import tempfile
from datetime import datetime, timedelta
from os import path
from typing import Optional

from pydantic import BaseModel
from pydantic.config import ConfigDict
from requests import get as GET

__version__ = "0.0.1"


ORIGIN = "http://iss.moex.com/iss"

USD_KEY = "CBRF_USD_LAST"

CACHE_FILE_PATH = path.join(tempfile.gettempdir(), f"{__name__}_cache_file")
CACHE_TTL = timedelta(minutes=5)


class Cbrf(BaseModel):
	columns: list[str]
	data: list[list[float | str]]

	model_config = ConfigDict(extra="ignore")


class Response(BaseModel):
	cbrf: Cbrf

	model_config = ConfigDict(extra="ignore")


def url(path: str) -> str:
	return ORIGIN + path


def make_parser() -> argparse.ArgumentParser:
	parser = argparse.ArgumentParser(
		description="Exchange USD to RUB from Moscow Exchange"
	)
	parser.add_argument("amount", nargs="*", default=[1], type=float)
	parser.add_argument(
		"-r", "--reverse", action="store_true", help="Exchange from RUB to USD"
	)
	parser.add_argument(
		"-V", "--version", action="version", version=f"usd2rub {__version__}"
	)
	return parser


def fetch_usd_price() -> float:
	resp = GET(url("/statistics/engines/currency/markets/selt/rates.json"))
	cbrf = Response(**json.loads(resp.content)).cbrf
	return float(cbrf.data[0][cbrf.columns.index(USD_KEY)])


def load_cached_usd_price() -> Optional[float]:
	try:
		mtime = datetime.fromtimestamp(path.getmtime(CACHE_FILE_PATH))
	except FileNotFoundError:
		return None
	elapsed = datetime.now() - mtime
	if elapsed > CACHE_TTL:
		return None
	with open(CACHE_FILE_PATH, "rb") as file:
		return pickle.load(file)


def cache_usd_price(price: float) -> None:
	with open(CACHE_FILE_PATH, "wb") as file:
		pickle.dump(price, file)


def get_usd_price() -> float:
	usd_price = load_cached_usd_price()
	if usd_price is not None:
		return usd_price
	usd_price = fetch_usd_price()
	cache_usd_price(usd_price)
	return usd_price


def main():
	parser = make_parser()
	args = parser.parse_args()
	usd_price = get_usd_price()
	fn = operator.truediv if args.reverse else operator.mul
	for amount in args.amount:
		print(f"{fn(amount, usd_price):.2f}")


if __name__ == "__main__":
	main()
